# org: lude1627
# app: fastapi-sls

service: fastapi-sls

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.12

functions:
  login:
    handler: handler.handler
    events:
      - httpApi:
          path: /login/sign_in
          method: post
  user:
    handler: handler.handler
    events:
      - httpApi:
          path: /user/register
          method: post
      - httpApi:
          path: /user/admin/register
          method: post
      - httpApi:
          path: /user/view/all
          method: get
      - httpApi:
          path: /user/view/{user_id}
          method: get
      - httpApi:
          path: /user/view/admin/{user_id}
          method: get
      - httpApi:
          path: /user/admin/update/{user_id}
          method: put
      - httpApi:
          path: /user/update
          method: put
  category:
    handler: handler.handler
    events:
      - httpApi:
          path: /category/create
          method: post
      - httpApi:
          path: /category/view/data
          method: get
      - httpApi:
          path: /category/update/{id}
          method: put
  product:
    handler: handler.handler
    events:
      - httpApi:
          path: /product/create
          method: post
      - httpApi:
          path: /product/view/data
          method: get
      - httpApi:
          path: /product/get_product/{id}
          method: get
      - httpApi:
          path: /product/edit/{id}
          method: put
      - httpApi:
          path: /product/delete/{id}
          method: put
  Carrito:
    handler: handler.handler
    events:
      - httpApi:
          path: /carro/agregar                             #agregar producto al carrito (usuario)
          method: post
      - httpApi:
          path: /carro/actualizar/{detalle_id}/{car_id}    #actualizar cantidad de un producto en el carrito (usuario)
          method: put
      - httpApi:
          path: /carro/{car_id}/estado                     #agregar estado a un carrito (admin)
          method: put
      - httpApi:
          path: /carro/view/all                            #listar todos los carritos (admin)
          method: get
      - httpApi:
          path: /carro/{car_id}/historial                  #obtener historial de estados de un carrito (admin)
          method: get
      - httpApi:
          path: /carro/usuario/{user_cc}                   #obtener carrito por usuario (usuario)
          method: get
      - httpApi:
          path: /carro/admin/{user_cc}                      #obtener un carrito por su ID (admin)
          method: get
      - httpApi:
          path: /carro/view/all/{user_cc}                  #listar todos los carritos de un usuario (usuario)
          method: get
      - httpApi:
          path: /carro/eliminar/{detalle_id}/{car_id}      #eliminar un producto del carrito (usuario)
          method: delete
      - httpApi:
          path: /carro/finalizar/{car_id}                  #finalizar compra del carrito (usuario)
          method: put
      - httpApi:
          path: /carro/dcarrito/{car_id}                   #ver detalles por carrito (usuario)
          method: get


          
