# org: lude1627
# app: fastapi-sls

service: fastapi-sls

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.12

functions:
  login:
    handler: handler.handler
    events:
      - httpApi:
          path: /login/sign_in
          method: post
  user:
    handler: handler.handler
    events:
      - httpApi:
          path: /user/register
          method: post
      - httpApi:
          path: /user/admin/register
          method: post
      - httpApi:
          path: /user/view/all
          method: get
      - httpApi:
          path: /user/view/{user_id}
          method: get
      - httpApi:
          path: /user/admin/update/{user_id}
          method: put
      - httpApi:
          path: /user/update
          method: put
  category:
    handler: handler.handler
    events:
      - httpApi:
          path: /category/create
          method: post
      - httpApi:
          path: /category/view/data
          method: get
      - httpApi:
          path: /category/update/{id}
          method: put
  product:
    handler: handler.handler
    events:
      - httpApi:
          path: /product/create
          method: post
      - httpApi:
          path: /product/view/data
          method: get
      - httpApi:
          path: /product/get_product/{id}
          method: get
      - httpApi:
          path: /product/edit/{id}
          method: put
      - httpApi:
          path: /product/delete/{id}
          method: put
  Carrito:
    handler: handler.handler
    events:
      - httpApi:
          path: /carro/agregar 
          method: post
      - httpApi:
          path: /carro/actualizar/{detalle_id}/{car_id}
          method: put
      - httpApi:
          path: /carro/{car_id}/estado
          method: put
      - httpApi:
          path: /carro/view/all
          method: get
      - httpApi:
          path: /carro/{user_cc}/historial
          method: get
      - httpApi:
          path: /carro/usuario/{user_cc}
          method: get
      - httpApi:
          path: /carro/eliminar/{detalle_id}/{car_id}
          method: delete
      - httpApi:
          path: /carro/finalizar/{car_id}
          method: put
      - httpApi:
          path: /carro/dcarrito/{car_id}
          method: get